//try catch para manejo de posibles errores

const numero1 = 20;
const numero2 = 30;

console.log(numero1);

try {
    console.log(numero2)
} catch (error) {
    console.log(error)
}

console.log(numero3);